
var local_data = {
    resturants: [{
        id: 0,
        name: "广东小厨",
        icon: "/images/sj/guangdongxiaochu/guangdongxiaochuicon.jpg",
        star: 3.9,
        sale: 999,
        diff:8,total_price:0,least_price: 8,
        for_tip: 1,
        distance: 555,
        time: "44分钟",
        discount: {
            cut: "满30减5，满50减10，满100减30",
            new_client: "新用户下单立减10元"
        },
        food_3: [{
            count: 0,
            url: "/images/sj/guangdongxiaochu/anchundan.jpg",
            name: "鹌鹑蛋",
            price: 4
        },
        {
            count: 0,
            url: "/images/sj/guangdongxiaochu/baocai.jpg",
            name: "白菜",
            price: 2
        }, {
            count: 0,
            url: "/images/sj/guangdongxiaochu/qiezi.jpg",
            name: "土豆",
            price: 4
        }
        ],
        food: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/guangdongxiaochu/anchundan.jpg",
            name: "鹌鹑蛋",
            price: 4,
            single_sale: 105,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/guangdongxiaochu/baocai.jpg",
            name: "白菜",
            price: 2,
            single_sale: 95,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/guangdongxiaochu/qiezi.jpg",
            name: "土豆",
            price: 4,
            single_sale: 180,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/zengdan.jpg",
            name: "蒸蛋",
            price: 5,
            single_sale: 59,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/jifen.jpg",
            name: "鸡粉",
            price: 6,
            single_sale: 125,
            single_value: 9.9,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }
        ],
        food_hot: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/guangdongxiaochu/anchundan.jpg",
            name: "鹌鹑蛋",
            price: 4,
            single_sale: 105,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/guangdongxiaochu/baocai.jpg",
            name: "白菜",
            price: 2,
            single_sale: 95,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/guangdongxiaochu/qiezi.jpg",
            name: "土豆",
            price: 4,
            single_sale: 180,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/zengdan.jpg",
            name: "蒸蛋",
            price: 5,
            single_sale: 59,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/jifen.jpg",
            name: "鸡粉",
            price: 6,
            single_sale: 125,
            single_value: 9.9,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_rice: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1290,
            single_value: 9.5,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/jipai/jiban.jpg",
            name: "鸡板",
            price: 6,
            single_sale: 195,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/jipai/jichuan.jpg",
            name: "鸡串",
            price: 5,
            single_sale: 111,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/jipai/jifen.jpg",
            name: "鸡粉",
            price: 4,
            single_sale: 98,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/jipai/jitui.jpg",
            name: "鸡腿",
            price: 5,
            single_sale: 209,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_full: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 6250,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/malatang/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 185,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/malatang/potatos.jpg",
            name: "土豆",
            price: 3,
            single_sale: 255,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/malatang/tudousi.jpg",
            name: "土豆丝",
            price: 3,
            single_sale: 190,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/malatang/youtiao.jpg",
            name: "油条",
            price: 3,
            single_sale: 59,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_delicious: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1250,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1250,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/waipojia/baocai.jpg",
            name: "包菜",
            price: 3,
            single_sale: 1005,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/waipojia/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 525,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/waipojia/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 1800,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/waipojia/tudousi.jpg",
            name: "土豆丝",
            price: 5,
            single_sale: 59,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_discount: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 2550,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 4450,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/shenxianbo/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 805,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/shenxianbo/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 695,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/shenxianbo/tudou.jpg",
            name: "土豆",
            price: 3,
            single_sale: 880,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/shenxianbo/tudousi.jpg",
            name: "土豆丝",
            price: 4,
            single_sale: 659,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 6,
            count: 0,
            url: "/images/sj/shenxianbo/zengdan.jpg",
            name: "蒸蛋",
            price: 3,
            single_sale: 1225,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }]

    }, {
        id: 1,
        name: "鸡排",
        icon: "/images/sj/jipai/jipaiicon.jpg",
        star: 4.5,
        sale: 899,
        diff:10,total_price:0,least_price: 10,
        for_tip: 1,
        distance: 666,
        time: "44分钟",
        discount: {
            cut: "满30减5，满50减10，满100减30",
            new_client: "新用户下单立减20元"
        },
        food_3: [{
            count: 0,
            url: "/images/sj/jipai/jiban.jpg",
            name: "鸡板",
            price: 6
        },
        {
            count: 0,
            url: "/images/sj/jipai/jichuan.jpg",
            name: "鸡串",
            price: 5
        }, {
            count: 0,
            url: "/images/sj/jipai/jifen.jpg",
            name: "鸡粉",
            price: 4
        }
        ],
        food: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1290,
            single_value: 9.5,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/jipai/jiban.jpg",
            name: "鸡板",
            price: 6,
            single_sale: 195,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/jipai/jichuan.jpg",
            name: "鸡串",
            price: 5,
            single_sale: 111,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/jipai/jifen.jpg",
            name: "鸡粉",
            price: 4,
            single_sale: 98,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/jipai/jitui.jpg",
            name: "鸡腿",
            price: 5,
            single_sale: 209,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }
        ], food_hot: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/guangdongxiaochu/anchundan.jpg",
            name: "鹌鹑蛋",
            price: 4,
            single_sale: 105,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/guangdongxiaochu/baocai.jpg",
            name: "白菜",
            price: 2,
            single_sale: 95,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/guangdongxiaochu/qiezi.jpg",
            name: "土豆",
            price: 4,
            single_sale: 180,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/zengdan.jpg",
            name: "蒸蛋",
            price: 5,
            single_sale: 59,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/jifen.jpg",
            name: "鸡粉",
            price: 6,
            single_sale: 125,
            single_value: 9.9,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_rice: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1290,
            single_value: 9.5,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/jipai/jiban.jpg",
            name: "鸡板",
            price: 6,
            single_sale: 195,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/jipai/jichuan.jpg",
            name: "鸡串",
            price: 5,
            single_sale: 111,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/jipai/jifen.jpg",
            name: "鸡粉",
            price: 4,
            single_sale: 98,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/jipai/jitui.jpg",
            name: "鸡腿",
            price: 5,
            single_sale: 209,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_full: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 6250,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/malatang/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 185,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/malatang/potatos.jpg",
            name: "土豆",
            price: 3,
            single_sale: 255,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/malatang/tudousi.jpg",
            name: "土豆丝",
            price: 3,
            single_sale: 190,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/malatang/youtiao.jpg",
            name: "油条",
            price: 3,
            single_sale: 59,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_delicious: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1250,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1250,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/waipojia/baocai.jpg",
            name: "包菜",
            price: 3,
            single_sale: 1005,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/waipojia/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 525,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/waipojia/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 1800,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/waipojia/tudousi.jpg",
            name: "土豆丝",
            price: 5,
            single_sale: 59,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_discount: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 2550,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 4450,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/shenxianbo/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 805,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/shenxianbo/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 695,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/shenxianbo/tudou.jpg",
            name: "土豆",
            price: 3,
            single_sale: 880,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/shenxianbo/tudousi.jpg",
            name: "土豆丝",
            price: 4,
            single_sale: 659,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 6,
            count: 0,
            url: "/images/sj/shenxianbo/zengdan.jpg",
            name: "蒸蛋",
            price: 3,
            single_sale: 1225,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }]
    }, {
        id: 2,
        name: "回味麻辣烫",
        icon: "/images/sj/malatang/malatangicon.gif",
        star: 4.8,
        sale: 3009,
        diff:16,total_price:0,least_price: 16,
        for_tip: 1,
        distance: 1055,
        time: "49分钟",
        discount: {
            cut: "满30减5，满50减10，满100减30",
            new_client: "新用户下单立减10元"
        },
        food_3: [{
            count: 0,
            url: "/images/sj/malatang/lianou.jpg",
            name: "莲藕",
            price: 3
        },
        {
            count: 0,
            url: "/images/sj/malatang/potatos.jpg",
            name: "土豆",
            price: 3
        }, {
            count: 0,
            url: "/images/sj/malatang/tudousi.jpg",
            name: "土豆丝",
            price: 3
        }
        ],
        food: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 6250,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/malatang/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 185,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/malatang/potatos.jpg",
            name: "土豆",
            price: 3,
            single_sale: 255,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/malatang/tudousi.jpg",
            name: "土豆丝",
            price: 3,
            single_sale: 190,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/malatang/youtiao.jpg",
            name: "油条",
            price: 3,
            single_sale: 59,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }
        ], food_hot: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/guangdongxiaochu/anchundan.jpg",
            name: "鹌鹑蛋",
            price: 4,
            single_sale: 105,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/guangdongxiaochu/baocai.jpg",
            name: "白菜",
            price: 2,
            single_sale: 95,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/guangdongxiaochu/qiezi.jpg",
            name: "土豆",
            price: 4,
            single_sale: 180,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/zengdan.jpg",
            name: "蒸蛋",
            price: 5,
            single_sale: 59,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/jifen.jpg",
            name: "鸡粉",
            price: 6,
            single_sale: 125,
            single_value: 9.9,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_rice: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1290,
            single_value: 9.5,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/jipai/jiban.jpg",
            name: "鸡板",
            price: 6,
            single_sale: 195,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/jipai/jichuan.jpg",
            name: "鸡串",
            price: 5,
            single_sale: 111,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/jipai/jifen.jpg",
            name: "鸡粉",
            price: 4,
            single_sale: 98,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/jipai/jitui.jpg",
            name: "鸡腿",
            price: 5,
            single_sale: 209,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_full: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 6250,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/malatang/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 185,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/malatang/potatos.jpg",
            name: "土豆",
            price: 3,
            single_sale: 255,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/malatang/tudousi.jpg",
            name: "土豆丝",
            price: 3,
            single_sale: 190,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/malatang/youtiao.jpg",
            name: "油条",
            price: 3,
            single_sale: 59,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_delicious: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1250,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1250,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/waipojia/baocai.jpg",
            name: "包菜",
            price: 3,
            single_sale: 1005,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/waipojia/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 525,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/waipojia/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 1800,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/waipojia/tudousi.jpg",
            name: "土豆丝",
            price: 5,
            single_sale: 59,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_discount: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 2550,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 4450,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/shenxianbo/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 805,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/shenxianbo/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 695,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/shenxianbo/tudou.jpg",
            name: "土豆",
            price: 3,
            single_sale: 880,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/shenxianbo/tudousi.jpg",
            name: "土豆丝",
            price: 4,
            single_sale: 659,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 6,
            count: 0,
            url: "/images/sj/shenxianbo/zengdan.jpg",
            name: "蒸蛋",
            price: 3,
            single_sale: 1225,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }]
    }, {
        id: 3,
        name: "神仙钵米饭",
        icon: "/images/sj/shenxianbo/shenxianboicon.jpg",
        star: 4.9,
        sale: 6850,
        diff:9,total_price:0,least_price: 9,
        for_tip: 1,
        distance: 1200,
        time: "48分钟",
        discount: {
            cut: "满30减5，满50减10，满100减30",
            new_client: "新用户下单立减10元"
        },
        food_3: [{
            count: 0,
            url: "/images/sj/shenxianbo/chaorou.jpg",
            name: "炒肉",
            price: 5
        },
        {
            count: 0,
            url: "/images/sj/shenxianbo/lianou.jpg",
            name: "莲藕",
            price: 3
        }, {
            count: 0,
            url: "/images/sj/shenxianbo/tudou.jpg",
            name: "土豆",
            price: 3
        }
        ],
        food: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 2550,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 4450,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/shenxianbo/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 805,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/shenxianbo/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 695,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/shenxianbo/tudou.jpg",
            name: "土豆",
            price: 3,
            single_sale: 880,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/shenxianbo/tudousi.jpg",
            name: "土豆丝",
            price: 4,
            single_sale: 659,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 6,
            count: 0,
            url: "/images/sj/shenxianbo/zengdan.jpg",
            name: "蒸蛋",
            price: 3,
            single_sale: 1225,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }
        ], food_hot: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/guangdongxiaochu/anchundan.jpg",
            name: "鹌鹑蛋",
            price: 4,
            single_sale: 105,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/guangdongxiaochu/baocai.jpg",
            name: "白菜",
            price: 2,
            single_sale: 95,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/guangdongxiaochu/qiezi.jpg",
            name: "土豆",
            price: 4,
            single_sale: 180,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/zengdan.jpg",
            name: "蒸蛋",
            price: 5,
            single_sale: 59,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/jifen.jpg",
            name: "鸡粉",
            price: 6,
            single_sale: 125,
            single_value: 9.9,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_rice: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1290,
            single_value: 9.5,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/jipai/jiban.jpg",
            name: "鸡板",
            price: 6,
            single_sale: 195,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/jipai/jichuan.jpg",
            name: "鸡串",
            price: 5,
            single_sale: 111,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/jipai/jifen.jpg",
            name: "鸡粉",
            price: 4,
            single_sale: 98,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/jipai/jitui.jpg",
            name: "鸡腿",
            price: 5,
            single_sale: 209,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_full: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 6250,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/malatang/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 185,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/malatang/potatos.jpg",
            name: "土豆",
            price: 3,
            single_sale: 255,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/malatang/tudousi.jpg",
            name: "土豆丝",
            price: 3,
            single_sale: 190,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/malatang/youtiao.jpg",
            name: "油条",
            price: 3,
            single_sale: 59,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_delicious: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1250,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1250,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/waipojia/baocai.jpg",
            name: "包菜",
            price: 3,
            single_sale: 1005,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/waipojia/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 525,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/waipojia/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 1800,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/waipojia/tudousi.jpg",
            name: "土豆丝",
            price: 5,
            single_sale: 59,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_discount: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 2550,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 4450,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/shenxianbo/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 805,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/shenxianbo/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 695,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/shenxianbo/tudou.jpg",
            name: "土豆",
            price: 3,
            single_sale: 880,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/shenxianbo/tudousi.jpg",
            name: "土豆丝",
            price: 4,
            single_sale: 659,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 6,
            count: 0,
            url: "/images/sj/shenxianbo/zengdan.jpg",
            name: "蒸蛋",
            price: 3,
            single_sale: 1225,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }]
    }, {
        id: 4,
        name: "外婆家",
        icon: "/images/sj/waipojia/waipojiaicon.jpg",
        star: 4.9,
        sale: 9899,
        diff:10,total_price:0,least_price: 10,
        for_tip: 1,
        distance: 1225,
        time: "40分钟",
        discount: {
            cut: "满30减5，满50减10，满100减30",
            new_client: "新用户下单立减10元"
        },
        food_3: [{
            count: 0,
            url: "/images/sj/waipojia/chaorou.jpg",
            name: "炒肉",
            price: 5
        }, {
            count: 0,
            url: "/images/sj/waipojia/lianou.jpg",
            name: "莲藕",
            price: 3
        }, {
            count: 0,
            url: "/images/sj/waipojia/tudousi.jpg",
            name: "土豆丝",
            price: 5
        }],
        food: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1250,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1250,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/waipojia/baocai.jpg",
            name: "包菜",
            price: 3,
            single_sale: 1005,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/waipojia/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 525,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/waipojia/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 1800,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/waipojia/tudousi.jpg",
            name: "土豆丝",
            price: 5,
            single_sale: 59,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }
        ], food_hot: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/guangdongxiaochu/anchundan.jpg",
            name: "鹌鹑蛋",
            price: 4,
            single_sale: 105,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/guangdongxiaochu/baocai.jpg",
            name: "白菜",
            price: 2,
            single_sale: 95,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/guangdongxiaochu/qiezi.jpg",
            name: "土豆",
            price: 4,
            single_sale: 180,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/zengdan.jpg",
            name: "蒸蛋",
            price: 5,
            single_sale: 59,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 5,
            count: 0,
            url: "/images/sj/guangdongxiaochu/jifen.jpg",
            name: "鸡粉",
            price: 6,
            single_sale: 125,
            single_value: 9.9,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_rice: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1850,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1290,
            single_value: 9.5,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/jipai/jiban.jpg",
            name: "鸡板",
            price: 6,
            single_sale: 195,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/jipai/jichuan.jpg",
            name: "鸡串",
            price: 5,
            single_sale: 111,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/jipai/jifen.jpg",
            name: "鸡粉",
            price: 4,
            single_sale: 98,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/jipai/jitui.jpg",
            name: "鸡腿",
            price: 5,
            single_sale: 209,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_full: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 800,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 6250,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 2,
            count: 0,
            url: "/images/sj/malatang/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 185,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/malatang/potatos.jpg",
            name: "土豆",
            price: 3,
            single_sale: 255,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/malatang/tudousi.jpg",
            name: "土豆丝",
            price: 3,
            single_sale: 190,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/malatang/youtiao.jpg",
            name: "油条",
            price: 3,
            single_sale: 59,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_delicious: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 1250,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 1250,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/waipojia/baocai.jpg",
            name: "包菜",
            price: 3,
            single_sale: 1005,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/waipojia/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 525,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/waipojia/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 1800,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/waipojia/tudousi.jpg",
            name: "土豆丝",
            price: 5,
            single_sale: 59,
            single_value: 9.1,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }],
        food_discount: [{
            food_id: 0,
            count: 0,
            url: "/images/sj/rice-2.jpg",
            name: "米饭",
            price: 1,
            single_sale: 2550,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 1,
            count: 0,
            url: "/images/sj/rice-3.jpg",
            name: "米饭",
            price: 1.5,
            single_sale: 4450,
            single_value: 9.6,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 2,
            count: 0,
            url: "/images/sj/shenxianbo/chaorou.jpg",
            name: "炒肉",
            price: 5,
            single_sale: 805,
            single_value: 9.0,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 3,
            count: 0,
            url: "/images/sj/shenxianbo/lianou.jpg",
            name: "莲藕",
            price: 3,
            single_sale: 695,
            single_value: 9.4,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 4,
            count: 0,
            url: "/images/sj/shenxianbo/tudou.jpg",
            name: "土豆",
            price: 3,
            single_sale: 880,
            single_value: 9.8,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }, {
            food_id: 5,
            count: 0,
            url: "/images/sj/shenxianbo/tudousi.jpg",
            name: "土豆丝",
            price: 4,
            single_sale: 659,
            single_value: 9.3,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        },
        {
            food_id: 6,
            count: 0,
            url: "/images/sj/shenxianbo/zengdan.jpg",
            name: "蒸蛋",
            price: 3,
            single_sale: 1225,
            single_value: 9.2,
            addicon: "/images/sj/add.jpg",
            deleteicon: "/images/sj/delete.jpg"
        }]
    }]
}
module.exports = {
    resturants: local_data.resturants
}
